steps:
- id: 'Rebuild Node Files'
  name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c' # pass what follows as a command to bash
  - |
    echo '{ "commitID":"$COMMIT_SHA", "buildID":"$BUILD_ID"}' > buildDetails
    npm install

- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_IMAGE_REPO/gcpdemo:$BUILD_ID', '.']
  waitFor: ['Rebuild Node Files']

- id: 'Push to GCR Container Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$_IMAGE_REPO/gcpdemo:$BUILD_ID"]
  waitFor: ['Create Container']

# Push container to Google GKE
- id: 'Deploy to GKE'
  name: 'gcr.io/cloud-builders/kubectl'
  waitFor: ['Push to GCR Container Registry']
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend-production'
  - 'webserver=gcr.io/$_IMAGE_REPO/gcpdemo:$BUILD_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'

# Push container to AWS EKS
- name: 'gcr.io/bkauf-cloud-build/panick-aws-tools'
  id: 'Deploy to EKS'
  waitFor: ['Push to GCR Container Registry']
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
     echo "Configuring AWS credentials and configs..."
     export AWS_ACCESS_KEY_ID=AKIAVGT4O7A2A6KZRXFC
     export AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_KEY
     export AWS_DEFAULT_REGION=us-east-2
     echo "Test file upload to S3"
     touch file-to-upload.txt
     aws s3 cp file-to-upload.txt s3://runcibleinc-s3-bucket/file-to-upload.txt
     echo "Configuring kubectl to point to EKS cluster"
     aws eks update-kubeconfig --name runcibleinc-eksctl # this updates kubeconfig to pull iam tokens using aws-cli
     kubectl set image deployment/frontend-production webserver=gcr.io/$_IMAGE_REPO/gcpdemo:$BUILD_ID
     echo "Deployment to EKS complete!"
  secretEnv: ['AWS_SECRET_KEY']

secrets:
- kmsKeyName: projects/prod-261517/locations/global/keyRings/multi-cloud-demo-keyring/cryptoKeys/primary-key
  secretEnv:
    AWS_SECRET_KEY: 'CiQADj/MCpwKMYGTiCloBMaYRBBDaPkKjSh7xPOHDAMSxRe8eroSUgCHA04IlnsTLx4GnxOVjfKgDny9ro8oBEKM2n3JlpSr+wEuoc2t4v0TZ0HiEZbp3Yo/WQhhgVdL0FGECd77NMmuiF3ue9W9Ts9FkYqc7ICiFHc='

#options:
# machineType: 'N1_HIGHCPU_8'
# diskSizeGb: 200
